# Generated by Django 4.2.25 on 2025-10-07 07:25

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('reference_count', models.IntegerField(default=1)),
                ('is_reference', models.BooleanField(default=False)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='files.file')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user_id', 'file_hash'], name='files_file_user_id_da50a1_idx')],
            },
        ),
    ]
